spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
bidforge.seed.demo-data=true
bidforge.scheduler.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
logging.level.com.bidforge=DEBUG
