CREATE TABLE roles
(
    id   NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT ck_roles_name CHECK (name IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE users
(
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR2(50 CHAR)           NOT NULL,
    email      VARCHAR2(150 CHAR)          NOT NULL,
    password   VARCHAR2(100 CHAR)          NOT NULL,
    first_name VARCHAR2(50 CHAR)           NOT NULL,
    last_name  VARCHAR2(50 CHAR)           NOT NULL,
    enabled    BOOLEAN                     NOT NULL,
    created_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);


CREATE TABLE user_roles
(
    user_id NUMBER(19, 0) NOT NULL,
    role_id NUMBER(19, 0) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);


CREATE TABLE auctions
(
    id                  NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    title               VARCHAR2(100 CHAR)          NOT NULL,
    description         VARCHAR2(2000 CHAR),
    category            VARCHAR2(20 CHAR)           NOT NULL,
    auction_type        VARCHAR2(20 CHAR)           NOT NULL,
    status              VARCHAR2(20 CHAR)           NOT NULL,
    starting_price      NUMBER(19, 2)               NOT NULL,
    min_increment       NUMBER(19, 2),
    current_highest_bid NUMBER(19, 2),
    start_time          TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    end_time            TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    seller_id           NUMBER(19, 0)               NOT NULL,
    created_at          TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_auctions PRIMARY KEY (id),
    CONSTRAINT fk_auctions_seller FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT ck_auctions_type CHECK (auction_type IN ('ENGLISH', 'SEALED_BID')),
    CONSTRAINT ck_auctions_status CHECK (status IN ('SCHEDULED', 'OPEN', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_auctions_category CHECK (category IN
                                           ('ELECTRONICS', 'VEHICLES', 'ART', 'COLLECTIBLES',
                                            'FASHION', 'BOOKS', 'SPORTS', 'OTHER'))
);


CREATE TABLE bids
(
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    amount     NUMBER(19, 2)               NOT NULL,
    auction_id NUMBER(19, 0)               NOT NULL,
    bidder_id  NUMBER(19, 0)               NOT NULL,
    created_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_bids PRIMARY KEY (id),
    CONSTRAINT fk_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions (id),
    CONSTRAINT fk_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users (id)
);


CREATE TABLE auction_results
(
    id             NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    auction_id     NUMBER(19, 0)               NOT NULL,
    winner_id      NUMBER(19, 0),
    winning_bid_id NUMBER(19, 0),
    final_price    NUMBER(19, 2),
    closed_at      TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_auction_results PRIMARY KEY (id),
    CONSTRAINT uk_auction_results_auction UNIQUE (auction_id),
    CONSTRAINT fk_auction_results_auction FOREIGN KEY (auction_id) REFERENCES auctions (id),
    CONSTRAINT fk_auction_results_winner FOREIGN KEY (winner_id) REFERENCES users (id),
    CONSTRAINT fk_auction_results_bid FOREIGN KEY (winning_bid_id) REFERENCES bids (id)
);
CREATE TABLE audit_events
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    actor       VARCHAR2(50 CHAR)           NOT NULL,
    action      VARCHAR2(30 CHAR)           NOT NULL,
    entity_type VARCHAR2(30 CHAR)           NOT NULL,
    entity_id   NUMBER(19, 0)               NOT NULL,
    details     VARCHAR2(500 CHAR),
    created_at  TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_audit_events PRIMARY KEY (id),
    CONSTRAINT ck_audit_action CHECK (action IN
        ('USER_REGISTERED', 'USER_STATUS_CHANGED', 'AUCTION_CREATED',
        'AUCTION_UPDATED', 'AUCTION_OPENED', 'AUCTION_CLOSED',
        'AUCTION_CANCELLED', 'BID_PLACED', 'WINNER_SELECTED')
)
    );


CREATE INDEX idx_auctions_status_end ON auctions (status, end_time);
CREATE INDEX idx_auctions_status_start ON auctions (status, start_time);
CREATE INDEX idx_auctions_seller ON auctions (seller_id);
CREATE INDEX idx_bids_auction_amount ON bids (auction_id, amount DESC, created_at ASC);
CREATE INDEX idx_bids_bidder ON bids (bidder_id);
CREATE INDEX idx_audit_entity ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_events (created_at);
