create table auction_results
(
    final_price    number(19, 2),
    auction_id     number(19, 0)               not null unique,
    closed_at      timestamp(9) with time zone not null,
    id             number(19, 0) generated by default as identity,
    winner_id      number(19, 0),
    winning_bid_id number(19, 0),
    primary key (id)
);
create table auctions
(
    current_highest_bid number(19, 2),
    min_increment       number(19, 2),
    starting_price      number(19, 2)               not null,
    created_at          timestamp(9) with time zone not null,
    end_time            timestamp(9) with time zone not null,
    id                  number(19, 0) generated by default as identity,
    seller_id           number(19, 0)               not null,
    start_time          timestamp(9) with time zone not null,
    updated_at          timestamp(9) with time zone not null,
    auction_type        varchar2(20 char)           not null check ((auction_type in ('ENGLISH', 'SEALED_BID'))),
    category            varchar2(20 char)           not null check ((category in
                                                                     ('ELECTRONICS', 'VEHICLES', 'ART', 'COLLECTIBLES',
                                                                      'FASHION', 'BOOKS', 'SPORTS', 'OTHER'))),
    status              varchar2(20 char)           not null check ((status in ('SCHEDULED', 'OPEN', 'CLOSED', 'CANCELLED'))),
    title               varchar2(100 char)          not null,
    description         varchar2(2000 char),
    primary key (id)
);
create table audit_events
(
    created_at  timestamp(9) with time zone not null,
    entity_id   number(19, 0)               not null,
    id          number(19, 0) generated by default as identity,
    action      varchar2(30 char)           not null check ((action in ('USER_REGISTERED', 'USER_STATUS_CHANGED',
                                                                        'AUCTION_CREATED', 'AUCTION_UPDATED',
                                                                        'AUCTION_OPENED', 'AUCTION_CLOSED',
                                                                        'AUCTION_CANCELLED', 'BID_PLACED',
                                                                        'WINNER_SELECTED'))),
    entity_type varchar2(30 char)           not null,
    actor       varchar2(50 char)           not null,
    details     varchar2(500 char),
    primary key (id)
);
create table bids
(
    amount     number(19, 2)               not null,
    auction_id number(19, 0)               not null,
    bidder_id  number(19, 0)               not null,
    created_at timestamp(9) with time zone not null,
    id         number(19, 0) generated by default as identity,
    primary key (id)
);
create table roles
(
    id   number(19, 0) generated by default as identity,
    name varchar2(20 char) not null unique check ((name in ('ROLE_USER', 'ROLE_ADMIN'))),
    primary key (id)
);
create table user_roles
(
    role_id number(19, 0) not null,
    user_id number(19, 0) not null,
    primary key (role_id, user_id)
);
create table users
(
    enabled    boolean                     not null,
    created_at timestamp(9) with time zone not null,
    id         number(19, 0) generated by default as identity,
    first_name varchar2(50 char)           not null,
    last_name  varchar2(50 char)           not null,
    username   varchar2(50 char)           not null unique,
    password   varchar2(100 char)          not null,
    email      varchar2(150 char)          not null unique,
    primary key (id)
);
create index idx_auctions_status_end on auctions (status, end_time);
create index idx_auctions_seller on auctions (seller_id);
create index idx_audit_entity on audit_events (entity_type, entity_id);
create index idx_audit_created on audit_events (created_at);
create index idx_bids_auction_amount on bids (auction_id, amount desc, created_at asc);
create index idx_bids_bidder on bids (bidder_id);
alter table if exists auction_results
    add constraint FKeyxv8ilteqeljuvjk8vhp407q foreign key (auction_id) references auctions;
alter table if exists auction_results
    add constraint FKgmy5arkf9iin42plct8980c8p foreign key (winner_id) references users;
alter table if exists auction_results
    add constraint FKm1qnp8bbcul3d69xamtbwvfhv foreign key (winning_bid_id) references bids;
alter table if exists auctions
    add constraint FKlu950hyc1m3wi2km1mlrcttw1 foreign key (seller_id) references users;
alter table if exists bids
    add constraint FKbm89m2gow82dotpnlcp7t3p5f foreign key (auction_id) references auctions;
alter table if exists bids
    add constraint FKmtrc6tnwawlpk1u2km6qnxbha foreign key (bidder_id) references users;
alter table if exists user_roles
    add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles
    add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
